version: "3.9"

services:
  database:
    image: postgres
    container_name: database_smurl
    restart: always
    ports:
      - 5432:5432
    environment:
      - URL_DB=
    volumes:
      - /var/lib/postgres

  app:
    build: .
    container_name: smurl
    restart: always
    environment:
      - SECRET_TOKEN=
      - SECRET_EMAIL_TOKEN=
      - EXPIRES_TOKEN=
      - GITHUB_CLIENT_SECRET=
      - FACEBOOK_SECRET=
      - GOOGLE_SECRET=
      - GMAIL_EMAIL=
      - GMAIL_PASSWORD=
    depends_on:
      - database
    ports:
      - 5000:5000

volumes:
  pgdata: